name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose (excluding pgadmin)
        run: docker-compose up -d --scale pgadmin=0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: 'jdk'
          cache: 'maven'

      - name: Wait for Database to be Ready
        run: |
          until docker exec postgres_container pg_isready -U postgres -d tododb; do
            echo "Waiting for database to be ready..."
            sleep 5
          done

      - name: Run tests
        run: mvn test

      - name: Shut Down Docker Compose
        run: docker-compose down